/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileMessage: typeof import('./src/components/showMessage/FileMessage.vue')['default']
    GlobalMenu: typeof import('./src/components/globalMenu.vue')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    ImageMessage: typeof import('./src/components/showMessage/ImageMessage.vue')['default']
    IMdiFlask: typeof import('~icons/mdi/flask')['default']
    IMdiMicrophoneOutline: typeof import('~icons/mdi/microphone-outline')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    Input: typeof import('./src/components/InputMessage/Input.vue')['default']
    InputEmoj: typeof import('./src/components/InputMessage/InputEmoj.vue')['default']
    InputImage: typeof import('./src/components/InputMessage/InputImage.vue')['default']
    InputText: typeof import('./src/components/InputMessage/InputText.vue')['default']
    InputVoice: typeof import('./src/components/InputMessage/InputVoice.vue')['default']
    LinkMessage: typeof import('./src/components/showMessage/LinkMessage.vue')['default']
    LocationMessage: typeof import('./src/components/showMessage/LocationMessage.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    MessageList: typeof import('./src/components/showMessage/messageList.vue')['default']
    MoreActions: typeof import('./src/components/InputMessage/moreActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/showMessage/test.vue')['default']
    TextMessage: typeof import('./src/components/showMessage/TextMessage.vue')['default']
    Video: typeof import('./src/components/video/video.vue')['default']
    VideoMessage: typeof import('./src/components/showMessage/VideoMessage.vue')['default']
    VirtualList: typeof import('./src/components/virtualList/VirtualList.vue')['default']
    VoiceMessage: typeof import('./src/components/showMessage/VoiceMessage.vue')['default']
  }
}
